### ISSUE TITLE
NASA CDF library checksum changed causing conda build to halt

### ISSUE THREAD

**Issue by smithara** [ESA-VirES/MagneticModel#38]
https://github.com/ESA-VirES/MagneticModel/blob/377d01ff20d95bd646e3b5abc96a306489927c13/libcdf/meta.yaml#L14

During the conda build:
```
 SHA256 mismatch: 'f5d7c2774d017cbb6f70d53a3b12149a52ace4fb089c1ed4ecd352aa6dca27b8' != 'aceb1263f1a1bf76e4adefc3a79bbe7d725e590b0938ab440bb3a64fe2f1417b'
```
It looks like https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/cdf38_0/unix/cdf38_0-dist-cdf.tar.gz changed at 2020-08-28 14:52

**Comment by pacesm** [comment]
Thanks. I'll check it. It should be easy to fix.

**Comment by pacesm** [comment]
The issue should be fixed now.

**Comment by smithara** [comment]
Confirmed working

**Comment by smithara** [comment]
The files at https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/cdf38_0/unix/ have changed again

**Comment by pacesm** [comment]
Thanks for the info. I'll update the hash.

**Comment by pacesm** [comment]
759fc56cb47c2f07b1bbe06c2588da1ac9cea3b3 should fix the issue.
