### ISSUE TITLE
Discard

### ISSUE THREAD

**Issue by hongbo-yao** [ESA-VirES/MagneticModel#50]

**Comment by pacesm** [comment]
@hongbo-yao The content seems to be removed. Is there anything we can help with?

**Comment by pacesm** [comment]
@hongbo-yao I've found your e-mail in my mail box and I'm going to respond to it.

**Comment by hongbo-yao** [comment]
> @hongbo-yao I've found your e-mail in my mail box and I'm going to respond to it.

@pacesm Thank you very much. I have solved this problem.
