### ISSUE TITLE
Add IGRF14

### ISSUE THREAD

**Issue by smithara** [ESA-VirES/MagneticModel#51]
The new IGRF has been issued so can be added now. The SHC file can be downloaded at ~https://zenodo.org/records/14012303/files/IGRF14.shc?download=1~  https://zenodo.org/records/14218973/files/IGRF14.shc?download=1

IGRF-14 covers the period 1900-2030.0 and replaces IGRF-13 which only covers 1900-2025.0

**Comment by pacesm** [comment]
included in the [v0.13.0 release](https://github.com/ESA-VirES/MagneticModel/releases/tag/eoxmagmod-0.13.0)

scheduled for next service release
